### ISSUE TITLE
Change diff > Github Comment Limit

### ISSUE THREAD

**Issue by seanturner026** [dag-andersen/argocd-diff-preview#42]
Hey Dag, this is something I noticed.

Really large changes greater than the 60k-ish Github Comment character limit get cut off. An easy work around to this is to add a step to the Github Action that `cat`s diff.md. Could accomplish this by updating the README.md.

I think another solution might be to do the following:

- After all apps are evaluated, count the characters in diff.md
- If > Github Character Limit, insert a line that says, `The diff is greater than the Github Comment character limit, please see <link to action that runs app> for your full diff near the top of diff.md.

What do you think? This is simple enough that I'm happy to take a crack at implementing. Thanks again for this groundbreaking tool!

**Comment by dag-andersen** [comment]
Hey @seanturner026! :)

Thank you for sharing your suggestions!

When a comment is cut off, what do you see?
The tool should already count the diff.md characters and display something like: `Diff is too long. Truncated to {} characters. This can be adjusted with the --max-diff-length flag` when the GitHub character limit is reached. If it doesn’t, then it's a bug! 💥

> If > Github Character Limit, insert a line that says, `The diff is greater than the Github Comment character limit, please see for your full diff near the top of diff.md.

Could you clarify what you mean by "near the top of diff.md"? I am not sure what this refers to 😄

**Comment by seanturner026** [comment]
> When a comment is cut off, what do you see?  The tool should already count the diff.md characters and display something like: Diff is too long. Truncated to {} characters. This can be adjusted with the --max-diff-length flag when the GitHub character limit is reached. If it doesn’t, then it's a bug! 💥

You're right, I forgot that the `diff is too long` comment does get introduced there. Here's an example.
https://github.com/seanturner026/argocd-applicationset/pull/27#issuecomment-2291868594

This all means that the "other solution" I referenced above is generally irrelevant.

> Could you clarify what you mean by "near the top of diff.md"? I am not sure what this refers to 😄

This was in reference to how the PR comment is the content of `diff.md`.

So instead of:

```
Summary:

 {base => target}/blah | 2711 ++++++++++++++++++++++++++-----
``` 

Perhaps:


```
Summary:

NOTE: Diff is too long. Truncated to {} characters. This can be adjusted with the --max-diff-length flag
 {base => target}/blah | 2711 ++++++++++++++++++++++++++-----
``` 

But as I mentioned I overlooked the fact that that line is already at the bottom, so there's really no difference here. I think we can close this.
