### ISSUE TITLE
Could you clarify the license?

### ISSUE THREAD

**Issue by johanneskastl** [dag-andersen/argocd-diff-preview#62]
Dear Dag,

could you please add a license, under which this project is available?

I find it a very interesting project! Nice work.

Kind Regards
Johannes

**Comment by dag-andersen** [comment]
Done ✅ I have set it to use the same license as the argo-cd project 🚀 
Thank you so much! Let me know if you try it out and have any feedback :) or if you encounter any issues

**Comment by dag-andersen** [comment]
I'll close the ticket 🤖 Feel free to reopen it if you have further comments :)

**Comment by johanneskastl** [comment]
Thanks a lot!
