### ISSUE TITLE
Support for repos with '_' and '.' characters

### ISSUE THREAD

**Issue by loadstar81** [dag-andersen/argocd-diff-preview#76]
Currently if a repo contains an underscore or period in it's name this tool errors out with:
```
❌ Invalid repository format. Please use OWNER/REPO
❌ Invalid repository format
Error: "Invalid repository format"
```

These are valid characters to use ([example here](https://github.com/loadstar81/.--__..--..__--.)) in a GH repository name

**Comment by dag-andersen** [comment]
This should now be released in version `0.0.26` [[release]](https://github.com/dag-andersen/argocd-diff-preview/releases/tag/v0.0.26) 🚀
